name: preloft_app
description: Aplikasi marketplace Preloft untuk jual beli barang preloved.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0

  # Routing
  go_router: ^13.2.1

  # Backend & Database
  supabase_flutter: ^2.5.1
  flutter_dotenv: ^5.2.1
  
  # UI & Utilities
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.1.0      # Untuk loading indicator
  intl: ^0.20.2               # Untuk format mata uang, dll.
  url_launcher: ^6.2.4        # Untuk membuka link eksternal
  image_picker: ^1.0.7        # Untuk memilih gambar
  uuid: ^4.3.3                # Untuk generate ID unik
  flutter_image_compress: ^2.2.0  # Untuk kompresi gambar
  path_provider: ^2.1.2         # Untuk mendapatkan direktori temporary

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/.env