name: marketplace_app
description: A Flutter marketplace app mirip Facebook Marketplace

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^13.2.1
  supabase_flutter: ^2.5.1
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.1.0
  intl: ^0.20.2
  url_launcher: ^6.2.4
  characters: ^1.3.0
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/.env # <-- Path diperbarui ke lib/.env
