name: marketplace_app
description: A Flutter marketplace app similar to Facebook Marketplace

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.1.3
  go_router: ^13.2.0
  supabase_flutter: ^2.5.1 # Using a common recent version as example
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.10
  intl: ^0.20.2
  flutter_spinkit: ^5.1.0
  characters: ^1.4.0 # Changed from ^1.4.1 to ^1.4.0 to resolve conflict with flutter_test
  js: ^0.7.2

  # UI & Utils
  # Other packages that showed available newer versions in your output

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
