// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxcMAHOHaQ03LrX_2uzJ_4WLNYeugvqQQ',
    appId: '1:418321155976:web:73196443b67909a98a9c3d',
    messagingSenderId: '418321155976',
    projectId: 'marketplace-flutter-app',
    authDomain: 'marketplace-flutter-app.firebaseapp.com',
    storageBucket: 'marketplace-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJY1eFMghEbntQ5K6PcAIRphApOOxoOA0',
    appId: '1:418321155976:android:4f5ceaa9f1bf0a488a9c3d',
    messagingSenderId: '418321155976',
    projectId: 'marketplace-flutter-app',
    storageBucket: 'marketplace-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyhDr_EkPIj7dgjNYaLGMLUJvjT9FHkRc',
    appId: '1:418321155976:ios:c36927d23e9e0ef28a9c3d',
    messagingSenderId: '418321155976',
    projectId: 'marketplace-flutter-app',
    storageBucket: 'marketplace-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyhDr_EkPIj7dgjNYaLGMLUJvjT9FHkRc',
    appId: '1:418321155976:ios:c36927d23e9e0ef28a9c3d',
    messagingSenderId: '418321155976',
    projectId: 'marketplace-flutter-app',
    storageBucket: 'marketplace-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxcMAHOHaQ03LrX_2uzJ_4WLNYeugvqQQ',
    appId: '1:418321155976:web:53d7b5b0a41b41f78a9c3d',
    messagingSenderId: '418321155976',
    projectId: 'marketplace-flutter-app',
    authDomain: 'marketplace-flutter-app.firebaseapp.com',
    storageBucket: 'marketplace-flutter-app.firebasestorage.app',
  );

}